import Link from 'next/link';
import { Instagram, Mail, MapPin, Phone } from 'lucide-react';

export default function Footer() {
  return <footer className="mt-20 bg-[#171717] text-white">
    <div className="market-container grid gap-10 py-12 md:grid-cols-[1.35fr_1fr_1fr_1.2fr]">
      <div><div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-[10px] bg-white text-xs font-bold text-[#4f6bff]">M</span><span className="leading-[1.05]"><strong className="block text-[14px] font-extrabold tracking-[-.04em]">mahathi</strong><small className="font-label text-[8px] uppercase tracking-[.16em] text-[#aaa]">tailor shop</small></span></div><p className="mt-5 max-w-[250px] text-[12px] leading-6 text-[#a9a6a3]">Indian occasionwear, everyday pieces, and the fit that makes them yours.</p><div className="mt-5 flex gap-2"><a href="#instagram" className="flex h-8 w-8 items-center justify-center rounded-full border border-[#3d3d3d] text-[#aaa] hover:text-white" aria-label="Instagram"><Instagram size={14} /></a><a href="mailto:hello@mahathitailor.in" className="flex h-8 w-8 items-center justify-center rounded-full border border-[#3d3d3d] text-[#aaa] hover:text-white" aria-label="Email us"><Mail size={14} /></a></div></div>
      <div><h3 className="font-label text-[9px] uppercase tracking-[.16em] text-[#d4af37]">Shop</h3><div className="mt-4 flex flex-col gap-3 text-[12px] text-[#c5c2bf]"><Link href="/shop">Shop all</Link><Link href="/shop?category=Sarees">Sarees</Link><Link href="/shop?category=Dresses">Dresses</Link><Link href="/shop?category=Bridal">Bridal</Link></div></div>
      <div><h3 className="font-label text-[9px] uppercase tracking-[.16em] text-[#d4af37]">Need a little help?</h3><div className="mt-4 flex flex-col gap-3 text-[12px] text-[#c5c2bf]"><a href="#size-guide">Size guide</a><a href="#shipping">Shipping & returns</a><a href="#care">Care instructions</a><Link href="/#services">Book a fitting</Link></div></div>
      <div><h3 className="font-label text-[9px] uppercase tracking-[.16em] text-[#d4af37]">Visit the studio</h3><div className="mt-4 flex flex-col gap-3 text-[12px] leading-5 text-[#c5c2bf]"><p className="flex gap-2"><MapPin size={15} className="mt-0.5 shrink-0 text-[#d4af37]" /> 8-2-293/82, Banjara Hills<br />Hyderabad, Telangana</p><p className="flex items-center gap-2"><Phone size={14} className="text-[#d4af37]" /> +91 90000 1998</p></div></div>
    </div>
    <div className="border-t border-[#2c2c2c] py-4"><div className="market-container flex flex-col justify-between gap-2 text-[9px] text-[#777] sm:flex-row"><span>© 2025 Mahathi Tailor Shop</span><span>Made in Hyderabad · Shipped with care</span></div></div>
  </footer>;
}